# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import os
import sys
import pprint

from snakemake.utils import validate
from snakemake.utils import min_version

min_version("9.0.0")

validate(config, "config.schema.yaml")
print("Config loaded:\n{}".format(config), file=sys.stderr)

MANIFEST = {}
for line in open(config["manifest"]):
    if line.startswith("#") or line.startswith("dsa"):
        continue  # skip comments and header
    tokens = line.strip().split()
    dsa = tokens[0]
    bam = tokens[1]
    h1_tag = tokens[2]
    h2_tag = tokens[3]
    if h1_tag == "NA":
        h1_tag = "h1"
    if h2_tag == "NA":
        h2_tag = "h2"
    sm_id = ".".join(os.path.basename(bam).split(".")[:-1])
    MANIFEST[sm_id] = {
        "dsa": dsa,
        "bam": bam,
        "h1_tag": h1_tag,
        "h2_tag": h2_tag,
    }

print("Manifest loaded with {} samples.".format(len(MANIFEST)), file=sys.stderr)
pprint.pprint(MANIFEST, depth=3, stream=sys.stderr)


MAX_THREADS = config.get("max_threads", 64)
DEFAULT_ENV = "../envs/env.yml"

SMs = list(MANIFEST.keys())


wildcard_constraints:
    sm="|".join(SMs),


include: "rules/common.smk"
include: "rules/dsa-phase.smk"


# build the list of needed outputs
needed_outputs = expand(rules.haplotag_and_sort.output.cram, sm=SMs)
if config.get("ont", False):
    needed_outputs += expand(rules.modkit.output.cram, sm=SMs)
needed_outputs += expand(rules.qc.output.txt, sm=SMs)

rule all:
    input:
        needed_outputs,
